#!/usr/bin/env bash
# Deploy posmp: provision the stack, wire the frontend to the API, upload the site.
#
# Prerequisites:
#   - AWS CLI configured (aws configure)
#   - AWS SAM CLI installed (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html)
#
# Usage:
#   ./deploy.sh                 # first run does a guided deploy, then remembers settings
#   STACK=my-shop ./deploy.sh   # custom stack name
set -euo pipefail

STACK="${STACK:-posmp}"
REGION="${REGION:-$(aws configure get region || echo us-east-1)}"

echo "==> Building Lambda"
sam build

echo "==> Deploying stack '$STACK' in $REGION"
if [ -f samconfig.toml ]; then
  sam deploy --stack-name "$STACK" --region "$REGION"
else
  # First deploy: ask for admin password + JWT secret interactively.
  sam deploy --guided --stack-name "$STACK" --region "$REGION" \
    --capabilities CAPABILITY_IAM
fi

echo "==> Reading stack outputs"
get_output() {
  aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}
API_URL="$(get_output ApiUrl)"
BUCKET="$(get_output SiteBucketName)"
DIST_ID="$(get_output DistributionId)"
SITE_URL="$(get_output SiteUrl)"

echo "==> Writing frontend/config.js"
cat > frontend/config.js <<EOF
// Generated by deploy.sh — do not edit by hand.
window.POSMP_CONFIG = { apiUrl: "${API_URL%/}" };
EOF

echo "==> Uploading site to s3://$BUCKET"
aws s3 sync frontend/ "s3://$BUCKET/" --delete \
  --exclude "config.example.js" \
  --region "$REGION"

echo "==> Invalidating CloudFront cache"
aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*" >/dev/null

echo ""
echo "Done. Your POS is live at:"
echo "  $SITE_URL"
echo ""
echo "API endpoint: $API_URL"
